complexity:
  NestedBlockDepth:
    threshold: 5
  TooManyFunctions:
    thresholdInClasses: 21
    thresholdInObjects: 21
    ignorePrivate: true
performance:
  SpreadOperator:
    active: false
style:
  MagicNumber:
    ignoreNumbers: ["-1", "0", "1", "2", "3", "4", "10", "16", "32"]
