name: on-release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  jdk-version: openjdk@~1.15.0
  project-name: Kt NPM Publish
  workflow: release
  gradle-options: "--no-daemon --console=plain --stacktrace"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #      - &cache_jdk
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-

      #      - &install_jdk
      - uses: battila7/jdk-via-jabba@v1
        name: Restore JDK
        with:
          jdk: ${{ env.jdk-version }}

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      #      - &checkout_code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Get All Tags
        run: git fetch --tags -f

      #      - *cache_jdk
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-

      #      - *install_jdk
      - uses: battila7/jdk-via-jabba@v1
        name: Restore JDK
        with:
          jdk: ${{ env.jdk-version }}

      #      - &cache_gradle
      - name: Cache Gradle Data
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/gradle/wrapper
            **/build
            **/.gradle
          key: ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-build
          restore-keys: |
            ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-build

      - name: Show Env
        run: ./gradlew --version

      - name: Setup Gradle
        run: ./gradlew ${{ env.gradle-options }}

      - name: Check Code Style
        run: ./gradlew ${{ env.gradle-options }} ktlintCheck

      - name: Archive KtLint Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ktlint-reports
          path: '**/build/reports/ktlint'

      - name: Check for Bugs
        run: ./gradlew ${{ env.gradle-options }} detekt

      - name: Compile
        run: ./gradlew ${{ env.gradle-options }} assemble --parallel

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      #      - *checkout_code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Get All Tags
        run: git fetch --tags -f

      #      - *cache_jdk
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-

      #      - *install_jdk
      - uses: battila7/jdk-via-jabba@v1
        name: Restore JDK
        with:
          jdk: ${{ env.jdk-version }}

      #      - *cache_gradle
      - name: Cache Gradle Data
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/gradle/wrapper
            **/build
            **/.gradle
          key: ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-test
          restore-keys: |
            ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-build

      - name: Test
        run: ./gradlew ${{ env.gradle-options }} test

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        if: failure() || success()
        with:
          name: jvm-test-reports
          path: '**/build/reports/tests/test'

  prepare-artifacts:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      #      - *checkout_code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Get All Tags
        run: git fetch --tags -f

      #      - *cache_jdk
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-

      #      - *install_jdk
      - uses: battila7/jdk-via-jabba@v1
        name: Restore JDK
        with:
          jdk: ${{ env.jdk-version }}

      #      - *cache_gradle
      - name: Cache Gradle Data
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/gradle/wrapper
            **/build
            **/.gradle
          key: ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-prepare
          restore-keys: |
            ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-test

      - name: Generate Doc
        run: ./gradlew ${{ env.gradle-options }} dokkaHtml --parallel

      - name: Sign Archives
        run: ./gradlew ${{ env.gradle-options }} signJava signKotlin --parallel
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.OSSRH_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - prepare-artifacts
    env:
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      #      - *checkout_code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history

      - name: Get All Tags
        run: git fetch --tags -f

      #      - *cache_jdk
      - name: Cache JDK
        uses: actions/cache@v2
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jdk-${{ env.jdk-version }}
          restore-keys: |
            ${{ runner.os }}-jdk-

      #      - *install_jdk
      - uses: battila7/jdk-via-jabba@v1
        name: Restore JDK
        with:
          jdk: ${{ env.jdk-version }}

      #      - *cache_gradle
      - name: Cache Gradle Data
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/gradle/wrapper
            **/build
            **/.gradle
          key: ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-maven-central
          restore-keys: |
            ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-prepare
            ${{ runner.os }}-${{ env.workflow }}-gradle-${{ github.sha }}-maven-

      - name: Publish Gradle Plugin
        run: ./gradlew ${{ env.gradle-options }} publishPlugin ${{ env.gradle-secrets }} --parallel
        #        if: contains(github.ref, 'master')
        env:
          gradle-secrets: "-Pgradle.publish.key=${{ secrets.GRADLE_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_SECRET }}"

      - name: Publish on Maven Central Repo
        run: ./gradlew ${{ env.gradle-options }} publishJavaMavenPublicationToSonatypeRepository --parallel
        #        if: contains(github.ref, 'master')
